<template>
  <Teleport to="body"><div v-if="isOpen" class="modal-backdrop" @click.self="close"><form class="modal-card" @submit.prevent="save"><div class="modal-head"><div><span>NEW TO YOUR LIBRARY</span><h2>Add a book</h2></div><button type="button" @click="close">×</button></div><p class="intro">Start with the essentials. You can add more detail anytime.</p><div class="form-grid"><label class="wide">Book title <input v-model.trim="form.title" required autofocus placeholder="e.g. The Creative Act"></label><label>Author <input v-model.trim="form.author" required placeholder="Author name"></label><label>Cover image <input v-model.trim="form.cover" type="url" placeholder="https://…"></label><label class="wide">Tags <input v-model="tags" placeholder="creativity, essays, favorites"></label><fieldset class="wide"><legend>Your rating</legend><StarRating v-model="form.stars" show-value /></fieldset></div><div class="modal-footer"><button type="button" class="cancel" @click="close">Cancel</button><button class="submit">Add to library</button></div></form></div></Teleport>
</template>
<script setup>
import { ref,watch } from 'vue'
import StarRating from './StarRating.vue'
import { useBooksStore } from '@/stores/books'
const props=defineProps({isOpen:Boolean}),emit=defineEmits(['close','book-added']),booksStore=useBooksStore()
const blank=()=>({title:'',author:'',cover:'',stars:0}),form=ref(blank()),tags=ref('')
const reset=()=>{form.value=blank();tags.value=''}
const close=()=>{reset();emit('close')}
const save=()=>{const book=booksStore.addBook({...form.value,tags:tags.value.split(',').map(t=>t.trim()).filter(Boolean)});emit('book-added',book);close()}
watch(()=>props.isOpen,value=>value&&reset())
</script>
<style scoped>
.modal-backdrop{position:fixed;inset:0;z-index:1000;padding:20px;display:grid;place-items:center;background:rgba(23,27,24,.63);backdrop-filter:blur(5px)}.modal-card{width:min(620px,100%);max-height:92vh;overflow:auto;padding:30px;border-radius:12px;background:#fbfaf6;box-shadow:0 30px 80px rgba(0,0,0,.3)}.modal-head{display:flex;justify-content:space-between}.modal-head span{color:#d95c3f;font-size:9px;font-weight:800;letter-spacing:.17em}.modal-head h2{margin:5px 0 0;font:500 31px Georgia,serif}.modal-head>button{width:34px;height:34px;border:1px solid #ded9ce;border-radius:50%;background:transparent;color:#77736b;font-size:20px}.intro{margin:10px 0 25px;color:#737168;font-size:12px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.wide{grid-column:1/-1}.form-grid label,.form-grid legend{color:#706c63;font-size:9px;font-weight:750;letter-spacing:.09em;text-transform:uppercase}.form-grid input{width:100%;height:42px;margin-top:7px;padding:0 12px;border:1px solid #ded9ce;border-radius:6px;background:white;outline:none;color:#24231f;font-size:12px;text-transform:none;letter-spacing:0}.form-grid input:focus{border-color:#7f8e78;box-shadow:0 0 0 3px rgba(89,107,86,.1)}fieldset{margin:3px 0 0;padding:12px 0 0;border:0;border-top:1px solid #e7e1d7}fieldset button{padding:0;border:0;background:transparent;color:#d39435;font-size:20px}fieldset small{margin-left:10px;color:#9a968d;font-size:9px}.modal-footer{margin-top:25px;padding-top:18px;border-top:1px solid #e7e1d7;display:flex;justify-content:flex-end;gap:8px}.modal-footer button{min-height:39px;padding:0 16px;border-radius:6px;font-size:11px;font-weight:700}.cancel{border:1px solid #ded9ce;background:transparent}.submit{border:1px solid #d95c3f;background:#d95c3f;color:white}@media(max-width:520px){.modal-card{padding:23px}.form-grid{grid-template-columns:1fr}.form-grid label{grid-column:1/-1}}
</style>
