<template>
  <Teleport to="body"><div v-if="isOpen" class="modal-backdrop" @click.self="close"><form class="modal-card" @submit.prevent="save"><div class="modal-head"><div><span>CAPTURE A PASSAGE</span><h2>New highlight</h2></div><button type="button" @click="close">×</button></div><p class="intro">Keep the exact words that made you pause.</p><div class="book-field"><span class="book-field-label">Book</span><BookPicker v-if="isOpen" v-model="form.bookId" :books="pickerBooks" :allow-all="false" :popup-layer="1100" /></div><label>Highlight<textarea v-model.trim="form.text" required rows="6" placeholder="Type or paste the passage here…"></textarea></label><div class="form-row"><label>Page <input v-model.number="form.page" type="number" min="1" placeholder="Optional"></label><label>Location or chapter <input v-model.trim="form.location" placeholder="Optional"></label></div><label class="favorite-check"><input v-model="form.isFavorite" type="checkbox"><span>Mark this as a favorite</span></label><div v-if="!books.length" class="warning">Add a book to your library before capturing a highlight.</div><div class="modal-footer"><button type="button" class="cancel" @click="close">Cancel</button><button class="submit" :disabled="!books.length || !form.bookId">Save highlight</button></div></form></div></Teleport>
</template>
<script setup>
import { computed,ref,watch } from 'vue'
import { useBooksStore } from '@/stores/books'
import { useQuotesStore } from '@/stores/quotes'
import BookPicker from './BookPicker.vue'
const props=defineProps({isOpen:Boolean,preselectedBookId:{type:String,default:null}}),emit=defineEmits(['close','quote-added'])
const booksStore=useBooksStore(),quotesStore=useQuotesStore(),books=computed(()=>booksStore.books)
const pickerBooks=computed(()=>books.value.map(book=>({...book,count:quotesStore.getQuotesByBook(book.id).length})))
const blank=()=>({bookId:props.preselectedBookId||'',text:'',page:null,location:'',isFavorite:false}),form=ref(blank())
const reset=()=>form.value=blank(),close=()=>{reset();emit('close')}
const save=()=>{if(!books.value.some(book=>book.id===form.value.bookId)||!form.value.text.trim())return;const quote=quotesStore.addQuote({...form.value});booksStore.addQuoteToBook(quote.bookId,quote.id);emit('quote-added',quote);close()}
watch(()=>props.isOpen,value=>value&&reset())
watch(()=>props.preselectedBookId,value=>{if(value)form.value.bookId=value})
</script>
<style scoped>
.book-field{margin-top:15px}.book-field-label{display:block;margin-bottom:8px;color:#706c63;font-size:12px;font-weight:750;letter-spacing:.09em;text-transform:uppercase}
.modal-backdrop{position:fixed;inset:0;z-index:1000;padding:20px;display:grid;place-items:center;background:rgba(23,27,24,.63);backdrop-filter:blur(5px)}.modal-card{width:min(620px,100%);max-height:92vh;overflow:auto;padding:30px;border-radius:12px;background:#fbfaf6;box-shadow:0 30px 80px rgba(0,0,0,.3)}.modal-head{display:flex;justify-content:space-between}.modal-head span{color:#d95c3f;font-size:9px;font-weight:800;letter-spacing:.17em}.modal-head h2{margin:5px 0 0;font:500 31px Georgia,serif}.modal-head>button{width:34px;height:34px;border:1px solid #ded9ce;border-radius:50%;background:transparent;color:#77736b;font-size:20px}.intro{margin:10px 0 25px;color:#737168;font-size:12px}.modal-card>label,.form-row label{display:block;margin-top:15px;color:#706c63;font-size:9px;font-weight:750;letter-spacing:.09em;text-transform:uppercase}.modal-card select,.modal-card textarea,.modal-card input[type=number],.modal-card input[type=text]{width:100%;margin-top:7px;padding:11px 12px;border:1px solid #ded9ce;border-radius:6px;background:white;outline:none;color:#24231f;font-size:12px;text-transform:none;letter-spacing:0}.modal-card textarea{resize:vertical;font:400 17px/1.55 Georgia,serif}.modal-card select:focus,.modal-card textarea:focus,.modal-card input:focus{border-color:#7f8e78;box-shadow:0 0 0 3px rgba(89,107,86,.1)}.form-row{display:grid;grid-template-columns:120px 1fr;gap:13px}.favorite-check{display:flex!important;align-items:center;gap:9px;text-transform:none!important;letter-spacing:0!important;font-size:11px!important}.favorite-check input{accent-color:#d95c3f}.warning{margin-top:15px;padding:12px;border-radius:6px;background:#f2dfd7;color:#9b402d;font-size:11px}.modal-footer{margin-top:25px;padding-top:18px;border-top:1px solid #e7e1d7;display:flex;justify-content:flex-end;gap:8px}.modal-footer button{min-height:39px;padding:0 16px;border-radius:6px;font-size:11px;font-weight:700}.cancel{border:1px solid #ded9ce;background:transparent}.submit{border:1px solid #d95c3f;background:#d95c3f;color:white}.submit:disabled{opacity:.4;cursor:not-allowed}@media(max-width:520px){.modal-card{padding:23px}.form-row{grid-template-columns:1fr}}
</style>
