<template>
  <Dialog :show="show" @update:show="emit('update:show',$event)">
    <div class="modal-head"><div><span>LIBRARY DATA</span><h2>Backup & restore</h2></div><button @click="emit('update:show',false)">×</button></div><p class="intro">Keep an independent copy of everything you’ve saved in Expclip.</p>
    <div class="data-options">
      <section><span class="option-icon">↓</span><div><h3>Create a backup</h3><p>Download all {{backupStats.books}} books and {{backupStats.quotes}} highlights as one JSON file.</p><button class="primary" :disabled="creatingBackup" @click="createBackup">{{creatingBackup?'Preparing…':'Download backup'}}</button><small v-if="backupMessage" :class="backupSuccess?'success':'error'">{{backupMessage}}</small></div></section>
      <section><span class="option-icon restore">↑</span><div><h3>Restore a backup</h3><p>Choose an Expclip backup file. Current data will only be replaced after confirmation.</p><label class="file-picker"><input ref="fileInput" type="file" accept=".json,application/json" @change="handleFileSelect"><span>{{selectedFile?selectedFile.name:'Choose backup file'}}</span><b>Browse</b></label><div v-if="restorePreview" class="preview"><span><b>{{restorePreview.books?.length||0}}</b> books</span><span><b>{{restorePreview.quotes?.length||0}}</b> highlights</span><small>Created {{formatDate(restorePreview.timestamp)}}</small></div><div class="restore-actions"><button v-if="selectedFile" @click="clearSelection">Clear</button><button class="primary" :disabled="!isValidBackup||restoring" @click="showRestoreConfirm=true">{{restoring?'Restoring…':'Restore this backup'}}</button></div><small v-if="restoreMessage" :class="restoreSuccess?'success':'error'">{{restoreMessage}}</small></div></section>
    </div>
  </Dialog>
  <Dialog :show="showRestoreConfirm" @update:show="showRestoreConfirm=$event"><div class="warning-mark">!</div><div class="confirm-copy"><span>REPLACE CURRENT DATA</span><h2>Restore this backup?</h2><p>Your current library will be replaced by <strong>{{restorePreview?.books?.length||0}} books</strong> and <strong>{{restorePreview?.quotes?.length||0}} highlights</strong> from the selected backup.</p></div><div class="confirm-actions"><button @click="showRestoreConfirm=false">Cancel</button><button class="danger" :disabled="restoring" @click="performRestore">{{restoring?'Restoring…':'Replace and restore'}}</button></div></Dialog>
</template>
<script setup>
import { ref,computed,watch } from 'vue'
import { useBooksStore } from '@/stores/books'
import { useQuotesStore } from '@/stores/quotes'
import BackupService from '@/services/BackupService'
import Dialog from './Dialog.vue'
const props=defineProps({show:Boolean}),emit=defineEmits(['update:show'])
const booksStore=useBooksStore(),quotesStore=useQuotesStore(),fileInput=ref(null)
const creatingBackup=ref(false),backupMessage=ref(''),backupSuccess=ref(false),selectedFile=ref(null),restorePreview=ref(null),isValidBackup=ref(false),restoring=ref(false),restoreMessage=ref(''),restoreSuccess=ref(false),showRestoreConfirm=ref(false)
const backupStats=computed(()=>({books:booksStore.bookCount,quotes:quotesStore.quoteCount}))
const createBackup=async()=>{creatingBackup.value=true;backupMessage.value='';try{backupSuccess.value=await BackupService.exportBackup();backupMessage.value=backupSuccess.value?'Backup downloaded successfully.':'Could not create the backup.'}catch(error){backupSuccess.value=false;backupMessage.value=error.message}finally{creatingBackup.value=false}}
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=e=>resolve(e.target.result);reader.onerror=reject;reader.readAsText(file)})
const handleFileSelect=async event=>{selectedFile.value=event.target.files[0]||null;restoreMessage.value='';if(!selectedFile.value)return clearSelection();try{const data=JSON.parse(await readFile(selectedFile.value)),validation=BackupService.validateBackup(data);if(!validation.valid)throw new Error(validation.errors.join(', '));restorePreview.value=data;isValidBackup.value=true}catch(error){restorePreview.value=null;isValidBackup.value=false;restoreSuccess.value=false;restoreMessage.value='This does not appear to be a valid Expclip backup.'}}
const performRestore=async()=>{if(!isValidBackup.value)return;restoring.value=true;showRestoreConfirm.value=false;try{const data=JSON.parse(await readFile(selectedFile.value));restoreSuccess.value=await BackupService.restoreFromBackup(data);restoreMessage.value=restoreSuccess.value?'Your library has been restored.':'The restore could not be completed.';if(restoreSuccess.value){selectedFile.value=null;restorePreview.value=null;isValidBackup.value=false;if(fileInput.value)fileInput.value.value=''}}catch(error){restoreSuccess.value=false;restoreMessage.value=error.message}finally{restoring.value=false}}
const clearSelection=()=>{selectedFile.value=null;restorePreview.value=null;isValidBackup.value=false;restoreMessage.value='';if(fileInput.value)fileInput.value.value=''}
const formatDate=value=>value?new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(value)):'Unknown date'
watch(()=>props.show,value=>{if(value){backupMessage.value='';restoreMessage.value=''}})
</script>
<style scoped>
.modal-head{display:flex;justify-content:space-between}.modal-head span,.confirm-copy>span{color:var(--accent);font-size:9px;font-weight:800;letter-spacing:.17em}.modal-head h2,.confirm-copy h2{margin:5px 0 0;font:500 31px Georgia,serif}.modal-head button{width:34px;height:34px;border:1px solid var(--line);border-radius:50%;background:transparent;color:#77736b;font-size:20px}.intro{margin:10px 0 25px;color:var(--muted);font-size:12px}.data-options{border-top:1px solid var(--line)}.data-options section{padding:24px 3px;display:grid;grid-template-columns:43px 1fr;gap:16px;border-bottom:1px solid var(--line)}.option-icon{width:39px;height:39px;display:grid;place-items:center;border-radius:8px;background:#dde5df;color:#385448;font-size:20px}.option-icon.restore{background:#eee2d0;color:#8b6030}.data-options h3{margin:0;font:600 16px Georgia,serif}.data-options p{margin:6px 0 15px;color:var(--muted);font-size:11px;line-height:1.55}.data-options button{min-height:36px;padding:0 13px;border:1px solid var(--line);border-radius:6px;background:transparent;font-size:10px;font-weight:700}.data-options .primary{border-color:var(--olive);background:var(--olive);color:white}.data-options button:disabled{opacity:.4;cursor:not-allowed}.data-options small{display:block;margin-top:10px;font-size:10px}.success{color:#397047}.error{color:#a64532}.file-picker{height:43px;padding-left:12px;border:1px solid #cfc9bd;border-radius:6px;display:flex;align-items:center;justify-content:space-between;background:white;color:#68645c;font-size:10px;cursor:pointer}.file-picker input{display:none}.file-picker b{height:100%;padding:0 13px;border-left:1px solid var(--line);display:grid;place-items:center;color:var(--accent)}.preview{margin-top:11px;padding:12px;display:flex;align-items:center;gap:16px;border-radius:6px;background:#eee9df;color:#68645c;font-size:10px}.preview span b{color:var(--ink);font:500 17px Georgia,serif}.preview small{margin:0 0 0 auto}.restore-actions{margin-top:11px;display:flex;justify-content:flex-end;gap:7px}.warning-mark{width:48px;height:48px;margin-bottom:20px;display:grid;place-items:center;border-radius:50%;background:#f0dcd6;color:#a94432;font:600 24px Georgia,serif}.confirm-copy p{margin:14px 0 0;color:var(--muted);font-size:12px;line-height:1.65}.confirm-actions{margin-top:27px;padding-top:18px;border-top:1px solid var(--line);display:flex;justify-content:flex-end;gap:8px}.confirm-actions button{min-height:39px;padding:0 15px;border:1px solid var(--line);border-radius:6px;background:transparent;font-size:11px;font-weight:700}.confirm-actions .danger{border-color:#a94532;background:#a94532;color:white}@media(max-width:500px){.data-options section{grid-template-columns:1fr}.preview{align-items:flex-start;flex-wrap:wrap}.preview small{width:100%;margin:0}}
</style>
